name: Macos

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["main"]
    paths:
      - "**.cpp"
      - "**.h"
      - "**.sc"

      - "src/**"
      - "include/**"
      - "shaders/**"

      - "CMakeLists.txt"
      - ".github/workflows/macos.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "**.cpp"
      - "**.h"
      - "**.sc"

      - "src/**"
      - "include/**"
      - "shaders/**"

      - "CMakeLists.txt"
      - ".github/workflows/macos.yml"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        c_compiler: [clang]
        include:
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
    steps:
      - name: Clone Repo
        uses: actions/checkout@v6

      - name: Cache Submodules
        id: cache-submodules
        uses: actions/cache@v5
        with:
          path: vendored
          key: ${{ runner.os }}-${{ hashFiles('.gitmodules') }}

      - name: Init Submodules
        run: git submodule update --init --recursive --depth 1
        if: steps.cache-submodules.outputs.cache-hit != 'true'

      - name: Install Dependencies
        # TODO: use brew SDL3 when new enough SDL3 releases
        run: |
          brew update
          brew install ccache glaze

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2.20
        with:
          variant: ccache
          create-symlink: true
          update-package-index: false
          key: ${{ runner.os }}-${{ runner.arch }}-ccache

      - name: Configure CMake
        if: ${{ runner.os != 'linux' }}
        run: >
          cmake -B build -G "Ninja Multi-Config"
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_C_COMPILER_LAUNCHER=ccache
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          -DBUILD_TESTING=ON

      - name: Build (Debug)
        run: cmake --build build --config Debug

      - name: Run Tests (Debug)
        working-directory: build
        run: ctest --build-config Debug
