name: Macos

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        c_compiler: [clang]
        include:
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2.20
        with:
          variant: ccache
          create-symlink: true
          update-package-index: false
          key: ${{ runner.os }}-${{ runner.arch }}-ccache

      - name: Install Dependencies
        # TODO: use brew SDL3 when new enough SDL3 releases
        run: |
          brew update
          brew install ccache glaze

      - name: Configure CMake
        if: ${{ runner.os != 'linux' }}
        run: >
          cmake -B build -G "Ninja Multi-Config"
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_C_COMPILER_LAUNCHER=ccache
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          -DBUILD_TESTING=ON

      - name: Build (Debug)
        run: cmake --build build --config Debug

      - name: Run Tests (Debug)
        working-directory: build
        run: ctest --build-config Debug
